import type { CertificateTemplate } from '../types/template.types';

export const DEFAULT_A4_PORTRAIT_TEMPLATE: Omit<CertificateTemplate, 'id' | 'createdAt' | 'updatedAt' | 'createdBy'> = {
  name: 'Classic A4 Portrait',
  description: 'Traditional bilingual certificate layout in portrait orientation',
  size: 'A4',
  orientation: 'portrait',
  width: 210,
  height: 297,
  
  background: {
    type: 'color',
    value: '#ffffff',
    opacity: 1,
  },
  
  border: {
    enabled: true,
    width: 3,
    color: '#1e40af',
    style: 'double',
    radius: 0,
    margin: 15,
  },
  
  theme: {
    primary: '#1e40af',
    secondary: '#3b82f6',
    accent: '#f59e0b',
    text: '#1f2937',
  },
  
  elements: [
    {
      id: 'logo',
      type: 'image',
      url: '/assets/logo.png',
      alt: 'Family Court Logo',
      position: { x: 95, y: 20, width: 20, height: 20 },
      zIndex: 10,
      visible: true,
      opacity: 1,
      fit: 'contain',
    },
    {
      id: 'title-en',
      type: 'text',
      content: 'Certificate of Completion',
      position: { x: 105, y: 50, width: 180 },
      zIndex: 10,
      visible: true,
      font: {
        family: 'Playfair Display, serif',
        size: 28,
        weight: 'bold',
        color: '#1e40af',
        lineHeight: 1.2,
      },
      align: 'center',
      language: 'en',
    },
    {
      id: 'subtitle-en',
      type: 'text',
      content: 'Marriage Awareness Program',
      position: { x: 105, y: 68, width: 180 },
      zIndex: 10,
      visible: true,
      font: {
        family: 'Open Sans, sans-serif',
        size: 16,
        weight: 'normal',
        color: '#4b5563',
      },
      align: 'center',
      language: 'en',
    },
    {
      id: 'subtitle-dv',
      type: 'text',
      content: 'ކައިވެންޏާ ބެހޭ ހޭލުންތެރިކަން އިތުރުކުރުމުގެ ޕްރޮގްރާމް',
      position: { x: 105, y: 78, width: 180 },
      zIndex: 10,
      visible: true,
      font: {
        family: 'MV Faseyha, sans-serif',
        size: 14,
        weight: 'normal',
        color: '#6b7280',
      },
      align: 'center',
      language: 'dv',
    },

    {
      id: 'body-intro',
      type: 'text',
      content: 'This is to certify that',
      position: { x: 105, y: 105, width: 180 },
      zIndex: 10,
      visible: true,
      font: {
        family: 'Open Sans, sans-serif',
        size: 13,
        weight: 'normal',
        color: '#6b7280',
      },
      align: 'center',
      language: 'en',
    },
    {
      id: 'participant-name',
      type: 'text',
      content: '',
      field: 'name',
      position: { x: 105, y: 120, width: 180 },
      zIndex: 10,
      visible: true,
      font: {
        family: 'Playfair Display, serif',
        size: 22,
        weight: 'bold',
        color: '#1e40af',
      },
      align: 'center',
      language: 'en',
    },
    {
      id: 'participant-name-dv',
      type: 'text',
      content: '',
      field: 'name_dv',
      position: { x: 105, y: 135, width: 180 },
      zIndex: 10,
      visible: true,
      font: {
        family: 'MV Faseyha, sans-serif',
        size: 16,
        weight: 'normal',
        color: '#374151',
      },
      align: 'center',
      language: 'dv',
    },
    {
      id: 'and-text',
      type: 'text',
      content: 'and',
      position: { x: 105, y: 152, width: 180 },
      zIndex: 10,
      visible: true,
      font: {
        family: 'Open Sans, sans-serif',
        size: 13,
        weight: 'normal',
        color: '#6b7280',
      },
      align: 'center',
      language: 'en',
    },
    {
      id: 'partner-name',
      type: 'text',
      content: '',
      field: 'partnerName',
      position: { x: 105, y: 165, width: 180 },
      zIndex: 10,
      visible: true,
      font: {
        family: 'Playfair Display, serif',
        size: 22,
        weight: 'bold',
        color: '#1e40af',
      },
      align: 'center',
      language: 'en',
    },
    {
      id: 'partner-name-dv',
      type: 'text',
      content: '',
      field: 'partnerName_dv',
      position: { x: 105, y: 180, width: 180 },
      zIndex: 10,
      visible: true,
      font: {
        family: 'MV Faseyha, sans-serif',
        size: 16,
        weight: 'normal',
        color: '#374151',
      },
      align: 'center',
      language: 'dv',
    },
    {
      id: 'completion-text-en',
      type: 'text',
      content: 'have successfully completed the Marriage Awareness Program',
      position: { x: 105, y: 205, width: 150 },
      zIndex: 10,
      visible: true,
      font: {
        family: 'Open Sans, sans-serif',
        size: 12,
        weight: 'normal',
        color: '#4b5563',
        lineHeight: 1.5,
      },
      align: 'center',
      language: 'en',
    },
    {
      id: 'completion-text-dv',
      type: 'text',
      content: 'މި ޕްރޮގްރާމް ކާމިޔާބުކަމާއެކު ފުރިހަމަކުރެއްވި ކަމަށް',
      position: { x: 105, y: 220, width: 150 },
      zIndex: 10,
      visible: true,
      font: {
        family: 'MV Faseyha, sans-serif',
        size: 11,
        weight: 'normal',
        color: '#6b7280',
      },
      align: 'center',
      language: 'dv',
    },
    {
      id: 'cert-number-label',
      type: 'text',
      content: 'Certificate No:',
      position: { x: 25, y: 260, width: 40 },
      zIndex: 10,
      visible: true,
      font: {
        family: 'Open Sans, sans-serif',
        size: 9,
        weight: 'normal',
        color: '#6b7280',
      },
      align: 'left',
      language: 'en',
    },
    {
      id: 'certificate-number',
      type: 'text',
      content: '',
      field: 'certificateNumber',
      position: { x: 45, y: 260, width: 50 },
      zIndex: 10,
      visible: true,
      font: {
        family: 'Open Sans, sans-serif',
        size: 9,
        weight: 'bold',
        color: '#1e40af',
      },
      align: 'left',
      language: 'en',
    },
    {
      id: 'date-label',
      type: 'text',
      content: 'Issue Date:',
      position: { x: 150, y: 260, width: 30 },
      zIndex: 10,
      visible: true,
      font: {
        family: 'Open Sans, sans-serif',
        size: 9,
        weight: 'normal',
        color: '#6b7280',
      },
      align: 'right',
      language: 'en',
    },
    {
      id: 'issue-date',
      type: 'text',
      content: '',
      field: 'issueDate',
      position: { x: 160, y: 260, width: 25 },
      zIndex: 10,
      visible: true,
      font: {
        family: 'Open Sans, sans-serif',
        size: 9,
        weight: 'normal',
        color: '#374151',
      },
      align: 'left',
      language: 'en',
    },
  ],
  
  signatures: [],
  stamps: [],
  
  version: 1,
  isDefault: true,
  isActive: true,
  
  printSettings: {
    margin: { top: 0, right: 0, bottom: 0, left: 0 },
    resolution: 300,
  },
};

export const DEFAULT_A4_LANDSCAPE_TEMPLATE: Omit<CertificateTemplate, 'id' | 'createdAt' | 'updatedAt' | 'createdBy'> = {
  ...DEFAULT_A4_PORTRAIT_TEMPLATE,
  name: 'Modern A4 Landscape',
  description: 'Contemporary bilingual certificate layout in landscape orientation',
  orientation: 'landscape',
  width: 297,
  height: 210,
};

export function createDefaultTemplate(
  orientation: 'portrait' | 'landscape' = 'portrait', 
  createdBy: string
): Omit<CertificateTemplate, 'id'> {
  const base = orientation === 'portrait' 
    ? DEFAULT_A4_PORTRAIT_TEMPLATE 
    : DEFAULT_A4_LANDSCAPE_TEMPLATE;
  
  return {
    ...base,
    createdBy,
    createdAt: new Date(),
    updatedAt: new Date(),
  };
}
